<?php get_header(); ?>
<?php get_sidebar(); ?>
<?php get_template_part('templates/page-header'); ?>
<?php get_template_part('templates/page-navbar'); ?>
<?php get_template_part('templates/page-navitems'); ?>
<?php get_template_part('templates/page-navmsg'); ?>
<?php get_template_part('templates/page-navuser'); ?>
<?php get_template_part('templates/content'); ?>
<?php get_footer(); ?>